markdown: kramdown
plugins:
  - jemoji
theme: minima
author: Tymoteusz Wołodźko
email: twolodzko+ghpage@gmail.com
github_username: twolodzko
google_analytics: G-V9DH8RH1V5
mastodon:
- username: tymwol
  instance: bayes.club
