project:
  type: website

website:
  title: "Timothy Wolodzko"
  navbar:
    right:
      - about.qmd
  google-analytics:
    tracking-id: G-V9DH8RH1V5
    storage: none
    anonymize-ip: true
    version: 3
format:
  html:
    theme: simplex
    css: styles.css
